 CREATE TABLE EMPLOYEES(
              EMPLOYEE_ID NUMBER(6) PRIMARY KEY,
              FIRST_NAME VARCHAR2(20)NOT NULL,
              LAST_NAME  VARCHAR2(25)NOT NULL,
              EMAIL VARCHAR2(25),
              PHONE_NUMBER VARCHAR2(20),
              HIRE_DATE DATE NOT NULL,
              JOB_ID VARCHAR2(10) NOT NULL,
              SALARY NUMBER(8, 2),
              COMMISSION_PCT NUMBER(2, 2),
              MANAGER_ID NUMBER(6) NOT NULL,
              DEPARTMENT_ID NUMBER(4)NOT NULL,
              CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID)
              REFERENCES EMPLOYEES (EMPLOYEE_ID),
              CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID)
              REFERENCES JOBS (JOB_ID),
              CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
              REFERENCES DEPARTMENTS (DEPARTMENT_ID)
              );

CREATE TABLE JOBS(
             JOB_ID VARCHAR2(10) PRIMARY KEY,
             JOB_TITLE VARCHAR2(35)NOT NULL,
             MIN_SALARY NUMBER(6),
             MAX_SALARY NUMBER(6)
             );

CREATE TABLE JOB_HISTORY(
             EMPLOYEE_ID NUMBER(6) PRIMARY KEY,
             START_DATE DATE PRIMARY KEY,
             END_DATE DATE,
             JOB_ID VARCHAR2(10) NOT NULL,
             DEPARTMENT_ID NUMBER(4) NOT NULL,
             CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID
             REFERENCES DEPARTMENTS (DEPARTMENT_ID)     
             CONSTRAINT JHIST_EMP_FK FOREIGN KEY (EMPLOYEE_ID)
             REFERENCES EMPLOYEES (EMPLOYEE_ID)
             CONSTRAINT PK_START_DATE PRIMARY KEY (START_DATE)            
             );
             
CREATE TABLE DEPARTMENTS(
             DEPARTMENT_ID NUMBER(4) PRIMARY KEY,
             DEPARTMENT_NAME VARCHAR2(30),
             MANAGER_ID NUMBER(6),
             LOCATION_ID NUMBER(4)NOT NULL,
             CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID)
             REFERENCES LOCATIONS (LOCATION_ID)
             );
 
CREATE TABLE REGIONS(
             REGION_ID NUMBER UNIQUE, 
             REGION_NAME VARCHAR2(25)
             );
             
CREATE TABLE COUNTRIES(
             COUNTRY_ID CHAR(2) PRIMARY KEY,
             COUNTRY_NAME VARCHAR2(40),
             REGION_ID NUMBER,
             CONSTRAINT COUNTR_REG_FK FOREIGN KEY (REGION_ID)
             REFERENCES REGIONS (REGION_ID)
             );

CREATE TABLE LOCATIONS(
             LOCATION_ID NUMBER(4) PRIMARY KEY,
             STREET_ADDRESS VARCHAR2(40),
             POSTAL_CODE VARCHAR2(12),
             CITY VARCHAR2(30) NOT NULL,
             STATE_PROVINCE VARCHAR2(25) NOT NULL,
             COUNTRY_ID CHAR(2) NOT NULL,
             CONSTRAINT CLOC_C_ID_FK FOREIGN KEY (COUNTRY_ID)
             REFERENCES COUNTRIES (COUNTRY_ID)
             );





